version: '3.9'

services:
  postgres-db:
    container_name: postgres-server
    image: "postgres"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: demo-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
  redis:
    container_name: redis
    image: "redis"
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  app:
    container_name: demo-api-app
    build: .
    ports:
      - "9090:9090"
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - redis
      - postgres-db
